name: Publish to cPanel on merge
"on":
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2.1.0 

    

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm clean-install

      - name: Build the React app
        run: npm run build

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD}}


      - name: Transfer build files to cPanel
        env:
          CPANEL_USER: ${{ secrets.FTP_USERNAME }}
          CPANEL_SERVER: ${{ secrets.FTP_SERVER }}
          CPANEL_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./build/ $CPANEL_USER@$CPANEL_SERVER:~/public_html/adextoapp

      - name: Start React app on cPanel
        env:
          CPANEL_USER: ${{ secrets.FTP_USERNAME }}
          CPANEL_SERVER: ${{ secrets.FTP_SERVER }}
          CPANEL_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no $CPANEL_USER@$CPANEL_SERVER << 'EOF'
          cd ~/public_html/adextoapp
          npm install
          nohup npm start &
          EOF